
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules/
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    networks:
      - network
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml


  x509-watch:
    container_name: x509-watch
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.22"
        VERSION: "dev"
        REVISION: "local"
    command:
      - "--listen=:9101"
      - "--cert-dir=/certs"
      - "--interval=1m"
      - "--log-level=info"
    volumes:
      - ../certs:/certs:ro
    ports:
      - "9101:9101"
    networks:
      - network

networks:
  network:

volumes:
  prometheus-storage: {}
  alertmanager-storage: {}

  
