global: 
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
  external_labels:
    replica: "prom-1"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"
      scheme: http
      api_version: v2
      timeout: 10s

rule_files:
  - "rules/prometheus_rules.yml"
  - "rules/postgresql_rules.yml"
  - "rules/node_exporter_rules.yml"
  - "rules/containers_rules.yml"
  - "rules/kubernetes_rules.yml"
  - "rules/traefik_rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: grafana
    static_configs:
      - targets:
          - "grafana:4000"

  - job_name: alertmanager
    static_configs:
      - targets:
          - "alertmanager:9093"
  
  
  - job_name: postgres
    static_configs:
      - targets:
          - "postgres_exporter:9187"
  
  - job_name: karma
    static_configs:
      - targets:
        - "karma:8080"

  # - job_name: "snak_server"
  #   metrics_path: '/api/metrics'
  #   http_sd_configs:
  #     - url: "http://localhost:3002/api/metrics"
  #       refresh_interval: "60s"
  #       follow_redirects: true
  #   static_configs:
  #     - targets: 
  #       - "localhost:3002"
      

