global: 
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
  external_labels:
    replica: "prom-1"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"
      scheme: http
      api_version: v2
      timeout: 10s

rule_files:
  - "rules/x509-watch_rules.yml"


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - "prometheus:9090"

  - job_name: alertmanager
    static_configs:
      - targets:
        - "alertmanager:9093"

  - job_name: karma
    static_configs:
      - targets:
        - "karma:8080"
  
  - job_name: x509-watch
    static_configs:
      - targets:
        - "x509-watch:9101"
      

